"""add image_url to categories

Revision ID: f9b54ffbb0e0
Revises: a10cc7856edb
Create Date: 2026-09-09 15:40:47.231568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9b54ffbb0e0'
down_revision: Union[str, Sequence[str], None] = 'a10cc7856edb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'image_url')
    # ### end Alembic commands ###
